# Generated by Django 6.1 on 2026-09-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_employeeprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='state',
            field=models.CharField(choices=[('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('auto_checked_out', 'Auto Checked Out')], default='checked_in', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_working_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
