# Generated by Django 6.1 on 2026-09-06 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shift'),
        ),
    ]
