# Generated by Django 6.1 on 2026-09-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_employeeprofile_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='shift_effective_from',
            field=models.DateField(blank=True, help_text='Date when this shift becomes effective', null=True),
        ),
    ]
