# Generated by Django 6.1 on 2026-09-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_employeeprofile_shift_effective_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='overtime_limit',
            field=models.IntegerField(default=2, help_text='Maximum overtime hours per day'),
        ),
    ]
