# Generated by Django 6.1 on 2026-09-07 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_shift_overtime_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_distance',
            field=models.PositiveIntegerField(blank=True, help_text='Distance from office in meters', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of check-in location', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of check-in location', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of check-out location', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of check-out location', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='attendance_type',
            field=models.CharField(choices=[('office', 'Office'), ('remote', 'Remote'), ('flexible', 'Flexible')], default='office', help_text='Office: requires location check. Remote/Flexible: no location restriction.', max_length=10),
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('allowed_radius', models.PositiveIntegerField(default=200, help_text='Radius in meters')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='office_location',
            field=models.ForeignKey(blank=True, help_text="Required if Attendance Type is 'Office'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.officelocation'),
        ),
    ]
