# Generated by Django 6.1.1 on 2026-09-08 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_attendance_check_in_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='The manager this employee reports to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='core.employeeprofile'),
        ),
    ]
