# Generated by Django 6.1.1 on 2026-09-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_employeeprofile_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('hr_admin', 'HR Admin')], default='employee', help_text='Employee role for permissions and approval routing', max_length=20),
        ),
    ]
