# Generated by Django 6.1.1 on 2026-09-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_company_payroll_enabled_employeesalary_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
