# Generated by Django 6.1.1 on 2026-09-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_shift_company_alter_shift_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together={('company', 'name')},
        ),
    ]
