# Generated by Django 6.1.1 on 2026-09-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_leavetype_name_alter_leavetype_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalary',
            name='deduction',
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pay per overtime hour in ₹', max_digits=10),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='other_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='paid_leave_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='payroll',
            name='present_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='unpaid_leave_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='payroll',
            name='unpaid_leave_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='working_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
