# Generated by Django 6.1.1 on 2026-09-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_employeesalary_deduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='absent_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='absent_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
