# Generated by Django 6.1.1 on 2026-09-13 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_attendance_options_alter_attendance_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeprofile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='is_company_owner',
            field=models.BooleanField(default=False, help_text='True for the primary HR Admin who self-approves their own requests.'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_self_approved',
            field=models.BooleanField(default=False, help_text='True when the requester self-approved as Company Owner.'),
        ),
        migrations.AddConstraint(
            model_name='employeeprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_company_owner', True)), fields=('company',), name='one_owner_per_company'),
        ),
    ]
