# Generated by Django 6.1.1 on 2026-09-13 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_employeeprofile_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='overtime_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Multiplier for OT rate. 1.50 = 1.5×, 2.00 = 2×.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
