# Generated by Django 6.1.1 on 2026-09-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_shift_overtime_multiplier_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='terminated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
