# Generated by Django 6.1.1 on 2026-09-16 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_employeeprofile_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedIPRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_prefix', models.CharField(max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'unique_together': {('company', 'ip_prefix')},
            },
        ),
    ]
