# Generated by Django 6.1.1 on 2026-09-16 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_allowediprange'),
    ]

    operations = [
        migrations.AddField(
            model_name='officelocation',
            name='allowed_ip_prefix',
            field=models.CharField(blank=True, help_text='First 3 octets of office WiFi IP (e.g. 49.36.180). Leave blank to require GPS only.', max_length=20),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='allowed_radius',
            field=models.IntegerField(default=200, help_text='Radius in meters'),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.DeleteModel(
            name='AllowedIPRange',
        ),
    ]
