# Generated by Django 6.1.1 on 2026-09-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_officelocation_allowed_ip_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='work_periods',
            field=models.JSONField(blank=True, default=list, help_text="List of work periods: [{'in': ISO string, 'out': ISO string or null}, ...]"),
        ),
    ]
