# Generated by Django 6.1.1 on 2026-09-16 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_attendance_work_periods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='work_periods',
        ),
    ]
