# Generated by Django 6.1.1 on 2026-09-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_attendance_work_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officelocation',
            name='allowed_ip_prefix',
            field=models.CharField(blank=True, help_text="Comma-separated IP prefixes (e.g. '127.0,103.159.42,49.36.180'). Leave blank to require GPS only.", max_length=500),
        ),
    ]
