# Generated by Django 6.1.1 on 2026-09-18 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_officelocation_allowed_ip_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateComingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('monthly_allowed_late_marks', models.PositiveIntegerField(default=3)),
                ('penalty_type', models.CharField(choices=[('leave', 'Deduct Leave'), ('salary', 'Deduct Salary'), ('none', 'No Penalty')], default='leave', max_length=10)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0.25, max_digits=5)),
                ('half_day_cutoff_minutes', models.PositiveIntegerField(default=45)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='late_coming_rule', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='RegularizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miss_punch_limit', models.PositiveIntegerField(default=3)),
                ('forgot_checkout_limit', models.PositiveIntegerField(default=3)),
                ('wrong_punch_limit', models.PositiveIntegerField(default=2)),
                ('other_limit', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regularization_rule', to='core.company')),
            ],
        ),
    ]
