# Generated by Django 6.1.1 on 2026-09-18 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_latecomingrule_regularizationrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularizationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('system_type', models.CharField(choices=[('miss_punch', 'Auto-detect: Miss Punch (no attendance row)'), ('forgot_checkout', 'Auto-detect: Forgot Checkout (in but no out)'), ('wrong_punch', 'Auto-detect: Wrong Check-in/out (both times present)'), ('other', 'Auto-detect: Other'), ('manual', 'Manual (employee chooses)')], default='manual', help_text='How this category is picked when an employee submits.', max_length=20)),
                ('monthly_limit', models.PositiveIntegerField(default=3, help_text='Max requests per employee per month.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_categories', to='core.company')),
            ],
            options={
                'verbose_name_plural': 'Regularization Categories',
                'ordering': ['order', 'id'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='regularizationrequest',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Which rule bucket this request falls under.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='core.regularizationcategory'),
        ),
    ]
