# Generated by Django 6.1.1 on 2026-09-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_regularizationcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='late_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='late_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='late_halfday_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='late_halfday_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
