# Generated by Django 6.1.1 on 2026-09-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_payroll_late_days_payroll_late_deduction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegularizationRule',
        ),
    ]
