# Generated by Django 6.1.1 on 2026-09-18 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_delete_regularizationrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Name shown in the dropdown, e.g. 'Miss Punch'.", max_length=100)),
                ('behavior', models.CharField(choices=[('miss_punch', 'No attendance row exists'), ('forgot_checkout', 'Checked in but never checked out'), ('wrong_punch', 'Both times present — wrong values'), ('other', 'Fallback / catch-all'), ('manual', 'Employee picks this manually')], default='manual', help_text='What the backend does when this type is picked.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_types', to='core.company')),
            ],
            options={
                'verbose_name_plural': 'Regularization Types',
                'ordering': ['order', 'id'],
                'unique_together': {('company', 'label')},
            },
        ),
        migrations.AlterField(
            model_name='regularizationcategory',
            name='system_type',
            field=models.ForeignKey(blank=True, help_text='Which HR-defined type this category belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='core.regularizationtype'),
        ),
    ]
