# Generated by Django 6.1.1 on 2026-09-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_regularizationtype_and_more'),
    ]

    operations = [
    ]
