# Generated by Django 6.1.1 on 2026-09-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_seed_reg_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularizationcategory',
            name='system_type',
        ),
    ]
