# Generated by Django 6.1.1 on 2026-09-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_regularizationcategory_system_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegularizationType',
        ),
    ]
