# Generated by Django 6.1.1 on 2026-09-18 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_delete_regularizationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='latecomingrule',
            name='calculation_method',
            field=models.CharField(choices=[('marks', 'Late Marks (simple)'), ('minutes', 'Late Minutes (precise)')], default='marks', help_text='How late arrivals are counted and penalized.', max_length=10),
        ),
        migrations.AddField(
            model_name='latecomingrule',
            name='insufficient_balance_action',
            field=models.CharField(choices=[('lop', 'Loss of Pay (LOP)'), ('skip', 'Skip Deduction')], default='lop', max_length=10),
        ),
        migrations.CreateModel(
            name='LateMinuteSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_minutes', models.PositiveIntegerField(help_text='Inclusive lower bound (e.g. 60).')),
                ('to_minutes', models.PositiveIntegerField(blank=True, help_text="Inclusive upper bound. Leave blank for 'and above'.", null=True)),
                ('penalty_days', models.DecimalField(decimal_places=2, default=0, help_text='Days of leave to deduct (e.g. 0.25 = quarter day).', max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minute_slabs', to='core.latecomingrule')),
            ],
            options={
                'verbose_name_plural': 'Late Minute Slabs',
                'ordering': ['order', 'from_minutes'],
            },
        ),
        migrations.CreateModel(
            name='RegularizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Name shown in the dropdown, e.g. 'Miss Punch'.", max_length=100)),
                ('behavior', models.CharField(choices=[('miss_punch', 'No attendance row exists'), ('forgot_checkout', 'Checked in but never checked out'), ('wrong_punch', 'Both times present — wrong values'), ('other', 'Fallback / catch-all'), ('manual', 'Employee picks this manually')], default='manual', help_text='What the backend does when this type is picked.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_types', to='core.company')),
            ],
            options={
                'verbose_name_plural': 'Regularization Types',
                'ordering': ['order', 'id'],
                'unique_together': {('company', 'label')},
            },
        ),
    ]
