# Generated by Django 6.1.1 on 2026-09-19 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_latecomingrule_calculation_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latecomingrule',
            name='target_leave_type',
            field=models.ForeignKey(blank=True, help_text='Which leave type absorbs late-arrival penalties. If empty, all penalties go to LOP.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_rules_using_this', to='core.leavetype'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='late_leave_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payroll',
            name='late_lop_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payroll',
            name='late_penalty_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
