# Generated by Django 6.1.1 on 2026-09-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_latecomingrule_target_leave_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='end_session',
            field=models.CharField(choices=[('full', 'Full Day'), ('first_half', 'First Half (Morning)'), ('second_half', 'Second Half (Afternoon)')], default='full', max_length=15),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_session',
            field=models.CharField(choices=[('full', 'Full Day'), ('first_half', 'First Half (Morning)'), ('second_half', 'Second Half (Afternoon)')], default='full', max_length=15),
        ),
    ]
