# Generated by Django 6.1.1 on 2026-09-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_leaverequest_end_session_leaverequest_start_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='half_day_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payroll',
            name='half_day_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
