# Generated by Django 6.1.1 on 2026-09-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_payroll_half_day_days_payroll_half_day_deduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='absent_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='present_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
