# Generated by Django 6.1.1 on 2026-09-24 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_payroll_absent_days_alter_payroll_present_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='pending_shift',
            field=models.ForeignKey(blank=True, help_text='Shift queued to take over on pending_shift_effective_from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_for_profiles', to='core.shift'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='pending_shift_effective_from',
            field=models.DateField(blank=True, help_text='Date when pending_shift becomes the active shift', null=True),
        ),
    ]
