# Generated by Django 6.1.1 on 2026-09-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_employeeprofile_pending_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='min_overtime_minutes',
            field=models.IntegerField(default=0, help_text='Minimum OT in minutes to count. Below this, OT is ignored (e.g. 30)'),
        ),
    ]
