# Generated by Django 6.1.1 on 2026-09-25 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_shift_min_overtime_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='The shift that was active on this date', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='core.shift'),
        ),
    ]
