# Generated by Django 6.1.1 on 2026-09-26 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_attendance_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(help_text='Date the employee was late (the attendance date)')),
                ('deduction_type', models.CharField(choices=[('LEAVE', 'Deduct Leave'), ('SALARY', 'Deduct Salary')], max_length=10)),
                ('penalty_days', models.DecimalField(decimal_places=2, max_digits=6)),
                ('leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('lop_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('salary_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('policy_snapshot', models.JSONField(blank=True, default=dict)),
                ('policy_ref_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('PENDING_PAYROLL', 'Pending Payroll'), ('PROCESSED', 'Processed'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('source', models.CharField(choices=[('LATE_COMING', 'Late Coming')], default='LATE_COMING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_deductions', to='core.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_deductions', to='core.employeeprofile')),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_deductions', to='core.leavetype')),
                ('payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_deductions', to='core.payroll')),
            ],
            options={
                'ordering': ['-attendance_date'],
                'indexes': [models.Index(fields=['company', 'attendance_date'], name='core_latede_company_7a1228_idx'), models.Index(fields=['employee', 'status'], name='core_latede_employe_efd8b0_idx'), models.Index(fields=['status', 'deduction_type'], name='core_latede_status_7b097b_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'attendance_date', 'source'), name='unique_late_deduction_per_day')],
            },
        ),
    ]
