# Generated by Django 6.1.1 on 2026-09-26 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_latededuction'),
    ]

    operations = [
        migrations.AddField(
            model_name='latecomingrule',
            name='effective_from',
            field=models.DateField(blank=True, help_text='Policy applies from this date onwards', null=True),
        ),
        migrations.AddField(
            model_name='latecomingrule',
            name='effective_to',
            field=models.DateField(blank=True, help_text='Policy applies up to this date (inclusive). Null = still active.', null=True),
        ),
        migrations.AddField(
            model_name='latecomingrule',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Auto-incremented when a new version is created'),
        ),
        migrations.AlterField(
            model_name='latecomingrule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_coming_rules', to='core.company'),
        ),
    ]
