# Generated by Django 6.1.1 on 2026-09-29 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_latecomingrule_effective_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDevicePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Require device verification for Clock In/Out')),
                ('max_mobile_devices', models.PositiveIntegerField(default=1)),
                ('max_laptop_devices', models.PositiveIntegerField(default=1)),
                ('allow_hr_override', models.BooleanField(default=True)),
                ('notify_hr_on_new_device', models.BooleanField(default=True)),
                ('allow_employee_self_remove', models.BooleanField(default=False)),
                ('allow_ip_fallback', models.BooleanField(default=True, help_text='If device fails, allow office IP as fallback')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('laptop', 'Laptop/Desktop')], max_length=10)),
                ('credential_id', models.BinaryField(max_length=255, unique=True)),
                ('public_key', models.BinaryField()),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('transports', models.CharField(blank=True, max_length=100)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disabled_attendance_devices', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used_at'],
                'indexes': [models.Index(fields=['user', 'device_type', 'is_active'], name='core_employ_user_id_2f7e78_idx')],
            },
        ),
    ]
