# Generated by Django 6.1.1 on 2026-09-30 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_attendancedevicepolicy_employeedevice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedevicepolicy',
            name='require_hr_approval',
            field=models.BooleanField(default=False, help_text='New devices require HR approval before activation'),
        ),
        migrations.AddField(
            model_name='attendancedevicepolicy',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_policy_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedevice',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedevice',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendance_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedevice',
            name='disabled_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employeedevice',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedevice',
            name='registration_status',
            field=models.CharField(choices=[('pending', 'Pending HR Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', help_text='HR approval status for this device', max_length=20),
        ),
        migrations.AddField(
            model_name='employeedevice',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='employeedevice',
            index=models.Index(fields=['company', 'registration_status'], name='core_employ_company_0cfa97_idx'),
        ),
    ]
