# Generated by Django 6.1.1 on 2026-09-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_attendancedevicepolicy_require_hr_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedevice',
            name='device_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
