# Generated by Django 6.1.1 on 2026-10-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_employeedevice_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='early_out_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minutes left before shift end'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_half_day',
            field=models.BooleanField(default=False, help_text='True if worked less than half of min working hours'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minutes late from shift start (after grace period)'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='missing_checkout',
            field=models.BooleanField(default=False, help_text='True if clock in but no clock out'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Overtime minutes worked beyond shift end'),
        ),
    ]
