# Generated by Django 6.1.1 on 2026-10-02 06:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_attendance_early_out_minutes_attendance_is_half_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularizationcategory',
            name='insufficient_balance_action',
            field=models.CharField(choices=[('lop', 'Loss of Pay (LOP)'), ('skip', 'Skip — waive remainder')], default='lop', help_text='What happens when leave balance is insufficient.', max_length=10),
        ),
        migrations.AddField(
            model_name='regularizationcategory',
            name='over_limit_action',
            field=models.CharField(choices=[('block', 'Block — cannot submit'), ('auto_deduct', 'Auto-Deduct on Quota Exhaustion')], default='block', help_text='What happens when employee exceeds the monthly limit.', max_length=20),
        ),
        migrations.AddField(
            model_name='regularizationcategory',
            name='penalty_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='0.5 = half day, 1.0 = full day. Applied per over-limit day.', max_digits=4),
        ),
        migrations.AddField(
            model_name='regularizationcategory',
            name='target_leave_type',
            field=models.ForeignKey(blank=True, help_text='Which leave type absorbs the penalty first.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_over_limit_deductions', to='core.leavetype'),
        ),
        migrations.AlterField(
            model_name='latededuction',
            name='source',
            field=models.CharField(choices=[('LATE_COMING', 'Late Coming'), ('REG_OVERAGE', 'Regularization over-limit')], default='LATE_COMING', max_length=20),
        ),
    ]
