# Generated by Django 6.1.1 on 2026-10-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_regularizationcategory_insufficient_balance_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularizationcategory',
            name='system_type',
            field=models.CharField(choices=[('miss_punch', 'Miss Punch — no attendance row'), ('forgot_checkout', 'Forgot Checkout — checked in, no checkout'), ('wrong_punch', 'Wrong Punch — wrong times'), ('short_hours', 'Short Hours — worked less than shift'), ('other', 'Other')], default='other', help_text='Attendance state this category handles.', max_length=30),
        ),
    ]
