# Generated by Django 6.1.1 on 2026-10-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_regularizationcategory_system_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularizationcategory',
            name='penalty_type',
            field=models.CharField(choices=[('leave', 'Deduct Leave'), ('salary', 'Deduct Salary')], default='leave', help_text='How the penalty is charged.', max_length=10),
        ),
    ]
