# Generated by Django 6.1.1 on 2026-10-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_attendance_check_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='device_tracking_enabled',
            field=models.BooleanField(default=False, help_text='Enable employee device management feature (Manage Devices).'),
        ),
    ]
