# Generated by Django 6.1.1 on 2026-10-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_company_device_tracking_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='face_registration_enabled',
            field=models.BooleanField(default=False, help_text='Enable face-recognition kiosk attendance for this company.'),
        ),
    ]
