# Generated by Django 6.1.1 on 2026-10-04 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_company_face_registration_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRegistrationConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('consent_version', models.CharField(default='1.0', help_text='Version of the consent form shown to employee', max_length=20)),
                ('employee_signature', models.CharField(blank=True, help_text='Employee typed their full name as consent', max_length=200)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_consents', to='core.company')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_consent', to='core.employeeprofile')),
                ('witnessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='witnessed_consents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KioskDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Main Gate, Factory Floor, Admin Block', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Physical location description', max_length=200)),
                ('device_token', models.CharField(help_text='Auto-generated secure token for device auth', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_clock_in', models.BooleanField(default=True)),
                ('allow_clock_out', models.BooleanField(default=True)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_devices', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kiosks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FaceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_1', models.BinaryField(help_text='Encrypted 128-dim vector')),
                ('vector_2', models.BinaryField()),
                ('vector_3', models.BinaryField()),
                ('vector_4', models.BinaryField()),
                ('vector_5', models.BinaryField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_matched_at', models.DateTimeField(blank=True, null=True)),
                ('match_count', models.PositiveIntegerField(default=0)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('match_threshold', models.FloatField(default=0.55, help_text='face-api.js euclidean distance threshold')),
                ('model_version', models.CharField(default='face-api-1.0', help_text='Which face-api.js model was used to register', max_length=20)),
                ('re_register_after', models.DateField(blank=True, help_text='Re-register every 12 months to account for aging', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_credentials', to='core.company')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_credential', to='core.employeeprofile')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_faces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'is_active'], name='core_facecr_company_b6e83c_idx'), models.Index(fields=['last_matched_at'], name='core_facecr_last_ma_7ce1e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='KioskAttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('in', 'Clock In'), ('out', 'Clock Out')], max_length=5)),
                ('result', models.CharField(choices=[('match', 'Matched'), ('no_match', 'No Match'), ('liveness_fail', 'Liveness Failed'), ('no_face', 'No Face Detected'), ('error', 'Error')], max_length=20)),
                ('confidence', models.FloatField(blank=True, help_text='Euclidean distance — lower is better', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk_logs', to='core.attendance')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_logs', to='core.company')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk_scans', to='core.employeeprofile')),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='core.kioskdevice')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['kiosk', '-timestamp'], name='core_kioska_kiosk_i_7e5bb4_idx'), models.Index(fields=['company', '-timestamp'], name='core_kioska_company_ee04a6_idx'), models.Index(fields=['employee', '-timestamp'], name='core_kioska_employe_7e67d9_idx'), models.Index(fields=['result'], name='core_kioska_result_a80372_idx')],
            },
        ),
        migrations.CreateModel(
            name='KioskSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.kioskdevice')),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['kiosk', 'is_active'], name='core_kiosks_kiosk_i_55855a_idx')],
            },
        ),
    ]
