# Generated by Django 6.1.1 on 2026-10-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_faceregistrationconsent_kioskdevice_facecredential_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskdevice',
            name='min_hours_before_out',
            field=models.DecimalField(decimal_places=1, default=2.0, help_text='Minimum hours between clock-in and clock-out', max_digits=4),
        ),
    ]
