# Generated by Django 6.1.1 on 2026-10-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_kioskdevice_min_hours_before_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskdevice',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='When the device was first activated', null=True),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='activation_pin',
            field=models.CharField(blank=True, help_text='Auto-generated 4-digit PIN for first-time activation', max_length=10),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='device_fingerprint',
            field=models.CharField(blank=True, help_text='Browser fingerprint stored at activation', max_length=200),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='is_activated',
            field=models.BooleanField(default=False, help_text='True after device enters correct PIN once'),
        ),
    ]
