# Generated by Django 6.1.1 on 2026-10-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_kioskdevice_activated_at_kioskdevice_activation_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='weekend_work_policy',
            field=models.CharField(choices=[('overtime', 'Paid as Overtime'), ('comp_off', 'Compensatory Off')], default='overtime', help_text='What happens when employee works on a weekend/holiday', max_length=20),
        ),
    ]
