# Generated by Django 6.1.1 on 2026-10-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_shift_weekend_work_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='weekend_ot_multiplier',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weekend/holiday OT multiplier. Leave 0 to use same as regular OT.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='shift',
            name='weekend_work_policy',
            field=models.CharField(choices=[('none', 'Not Allowed'), ('overtime', 'Paid as Overtime'), ('comp_off', 'Compensatory Off')], default='overtime', help_text='What happens when employee works on a weekend/holiday', max_length=20),
        ),
    ]
