# Generated by Django 6.1.1 on 2026-10-08 04:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_shift_weekend_ot_multiplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompOffCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_on', models.DateField()),
                ('days_credited', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=4)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('used_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp_off_credit', to='core.attendance')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_offs', to='core.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_offs', to='core.employeeprofile')),
                ('used_in_leave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_comp_offs', to='core.leaverequest')),
            ],
            options={
                'ordering': ['-earned_on'],
                'indexes': [models.Index(fields=['employee', 'status'], name='core_compof_employe_e98013_idx'), models.Index(fields=['company', 'status'], name='core_compof_company_43e1c6_idx')],
            },
        ),
    ]
