# Generated by Django 6.1.1 on 2026-10-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_compoffcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='regular_ot_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='regular_ot_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='payroll',
            name='weekend_ot_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='weekend_ot_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='payroll',
            name='weekend_ot_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
