# Generated by Django 6.1.1 on 2026-10-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_payroll_regular_ot_amount_payroll_regular_ot_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_overnight',
            field=models.BooleanField(default=False, help_text='Check if this shift crosses midnight (e.g., 22:00 → 06:00)'),
        ),
    ]
